### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by craciunchan** [gamingbet/Gamingbet#1]
can you please help me?
Parse error: syntax error, unexpected '{' in /home/vipsmzpx/public_html/mycoinreview.com/scripts/Gamingbet-master/_class/Language.class.php on line 92
and also at port' => 3306?

**Comment by hitch90** [comment]
sorry i'm not a authoer of this script. I bought it and share ;)

**Comment by hitch90** [comment]
Hi!

I fixed it :) And upload working database structure.
